### ISSUE TITLE
[New Feature] Add aggregate operations to manipulate/change data within the documents/records

### ISSUE THREAD

**Issue by iwu021** [CS180-spring/cs180-22-null#12]
[As a client, I want to perform aggregate operations on my data such as Max/Min in order to analyze them.#11](https://github.com/CS180-spring/cs180-22-null/issues/11)

Review: Cole Shirakata

**Comment by cwong165** [comment]
Sorry, made a mistake when updating info. I would fix it later

**Comment by iwu021** [comment]
![Image](https://github.com/CS180-spring/cs180-22-null/assets/81645935/6c0ce7d1-2415-462e-b79c-120fa9f6353c)
