### ISSUE TITLE
[MINOR BUG FIX]  Mutiple document menu refine Fix Menu Loop, Allow user return to log in menu after log out.#44

### ISSUE THREAD

**Issue by cwong165** [CS180-spring/cs180-22-null#34]
[As a user, I want to have fancy user interfact during selecting menu.#39](https://github.com/CS180-spring/cs180-22-null/issues/39)

review: Irene Wu

**Comment by cwong165** [comment]
![Image](https://user-images.githubusercontent.com/77028662/236460850-a87fa432-763f-4b55-98c7-0c6b633aa176.png)

**Comment by iwu021** [comment]
![Image](https://github.com/CS180-spring/cs180-22-null/assets/81645935/f5f4dd44-8103-4edf-9a69-a658af997a1d)
