### ISSUE TITLE
[New Feature]  Display a single record

### ISSUE THREAD

**Issue by cwong165** [CS180-spring/cs180-22-null#47]
[As a user, I want to be able to select a file and view its contents.](https://github.com/CS180-spring/cs180-22-null/issues/55)

Review: Irene Wu

**Comment by iwu021** [comment]
![Image](https://github.com/CS180-spring/cs180-22-null/assets/81645935/923b2a8f-3ef0-4c50-b661-a4a80e21b009)

If fixed, it is good to go
